### ISSUE TITLE
Bug on statistics on triangular matrices

### ISSUE THREAD

**Issue by gzagatti** [JuliaLang/Statistics.jl#107]
It looks like that some statistics on triangular matrices are not returning what I would expect to be the right result. For example, define the matrix `B`

```julia
julia> B = [0 1; 1 0]
×2 Matrix{Int64}:
 0  1
 1  0
```

If we take the mean of the lower triangle, we get:

```julia 
julia> LowerTriangular(B)
2×2 LowerTriangular{Int64, Matrix{Int64}}:
 0  ⋅
 1  0
julia> mean(LowerTriangular(B))
0.25
```

However, I would expect it to return `0.33`, since:
```julia
julia> mean([0, 0, 1])
0.3333
```

It looks like Julia is not respecting the masks set by `LowerTriangular`, but also by `tril`. What is the consensus here?

```julia
julia>  versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, icelake-client)
``

**Comment by ararslan** [comment]
This looks like the correct behavior to me. Conceptually, a lower triangular matrix is one for which all entries except those in the lower triangle are zero. You still have the same number of total elements, it's just that many are zero. In particular:
```julia
julia> L = LowerTriangular(B)
2×2 LowerTriangular{Int64, Matrix{Int64}}:
 0  ⋅
 1  0

julia> length(L)  # `length` is documented to return the number of elements in the array
4

julia> isassigned(L, 2, 2)  # the upper triangle is still valid for indexing
true

julia> L[2, 2]  # the value is 0, as expected
0
```
The mean of a collection is the sum of the elements divided by the number of elements, and the above shows that there is indeed four elements, so `mean(L)` should be (0 + 1 + 0 + 0) / 4 = 0.25.

**Comment by palday** [comment]
I agree with @ararslan here:

```julia
julia> Matrix(LowerTriangular(B))
2×2 Matrix{Int64}:
 0  0
 1  0

julia> Matrix(LowerTriangular(B)) == LowerTriangular(B)
true
```

The thing to remember is that the `.` in the shown values for matrices with a particular structure are *structural zeros* not undefined/missing/absent values.

**Comment by gzagatti** [comment]
The arguments above make sense. What got me confused was the `.` representation as it appeared to me that the structural zeros would not be taken into account in the computation. Perhaps the documentation could remind the user about that to avoid ambiguities?

With that being said, I still need to compute statistics on the non-structurally zero parts of the matrix. It would be useful to have a function to extract these numbers as a vector, since `vec` returns the vectorization of the matrix. A good candidate would be to have the `nonzeros` function (and possibly related functions) from `SparseArrays` also work on matrices with structural zero produced by the `LinearAlgebra` package. Would that make sense?

**Comment by palday** [comment]
If you're just doing  the lower triangle of (square) matrices, it's pretty straightforward:

```julia
julia> mean(B[i, j] for i in axes(B, 1) for j in 1:i) #1:(i-1) if you don't want the diagonal.
0.3333333333333333
```

If you really want an extra method, I think something analogous to `tril` but that returns the flattened lower triangle would make more sense than `nonzeros`. Maybe `lowertriangle`? But that seems like a method that doesn't need to be in LinearAlgebra itself.

**Comment by gzagatti** [comment]
Thanks for the suggestions. The one liner that you shared will do the job in my case.

My suggestion of having a method for extracting the non-structural zeros from matrices produced by `LinearAlgebra` would cover all other methods that return such matrices. Just going through the Linear Algebra documentation I see a plethora of them (`factorize`, `Diagonal`, `Tridiagonal`, `UniformScaling`, `Cholesky`, etc.). It can be tricky and finicky to get the loop index right, so a general method could be very useful. But I think this might be the topic for another issue.
