### ISSUE TITLE
Wrong docstring for Statistics.mean

### ISSUE THREAD

**Issue by cossio** [JuliaLang/Statistics.jl#109]
Docstring for `mean` says that:

>   mean(f::Function, itr)
>  Apply the function f to each element of collection itr and take the mean.

However, `mean` also works with callable structs, not just `f::Function`.

The docstring should be updated to reflect that.

**Comment by nalimilan** [comment]
Right. I've just filed https://github.com/JuliaLang/Statistics.jl/pull/110, which makes the minimal change of removing `::Function`. This is consistent with the docstring for `sum`. "Function" is probably clearer for users than "callable" and the signature conveys the fact that any type is accepted for `f`.
