### ISSUE TITLE
Add additional quantile estimators

### ISSUE THREAD

**Issue by lungben** [JuliaLang/Statistics.jl#18]
Currently, the quantile estimator definition 7 of 
Hyndman, R.J and Fan, Y. (1996) "Sample Quantiles in Statistical Packages",
  *The American Statistician*, Vol. 50, No. 4, pp. 361-365
is used for quantile calculation.

I suggest to add a generic quantile estimator method with alpha and beta as free parameters, so that the definitions 4-9 in the paper above can be used.

The following code gives the correct results (tested against SciPy), but has slightly worse performance than the current implementation (therefore I am hestitating to do a PR for now):

```
function Statistics.quantile!(v:: AbstractVector, p:: Real, alphap:: Real, betap:: Real; sorted:: Bool=false)
    0 <= p <= 1 || throw(ArgumentError("input probability out of [0,1] range"))
    0 <= alphap <= 1 || throw(ArgumentError("alpha parameter out of [0,1] range"))
    0 <= betap <= 1 || throw(ArgumentError("beta parameter out of [0,1] range"))
    require_one_based_indexing(v)
    
    if !sorted
        sort!(v)
    end
    n = length(v)
    m = alphap + p * (one(alphap) - alphap - betap)
    aleph = (n * p + m)
    k = min(max(Int(trunc(aleph)), 1), n - 1)
    gamma = min(max(aleph - k, zero(aleph)), one(aleph))
    return @inbounds (one(gamma) - gamma) * v[k] + gamma * v[k+1]
end

function Statistics.quantile(v:: AbstractVector, p:: Real, alphap:: Real, betap:: Real; sorted:: Bool=false)
    if !sorted
        v=copy(v)
    end
    Statistics.quantile!(v, p, alphap, betap, sorted=sorted)
end
```

Happy to discuss!

**Comment by nalimilan** [comment]
Sure, why not. To avoid performance regressions, you could use `alphap::Union{Real,Nothing}=nothing`, and keep the existing code when `alphap=nothing`.

In terms of API, maybe it would be simpler for users to support a list of possible estimators (instead of two parameters)? AFAIK that's what other software does (R and NumPy at least).

**Comment by lungben** [comment]
Thanks for the comments, I created a pull request.
#20 
I like your idea regarding named estimators (perhaps even referencing quantile estimators of other software, such as Matlab, R, Excel's PERCENTILE.INC and PERCENTILE.EXC), but had no time to do this it yet.
Probably, the best way for this would be an additional quantile method taking estimator name as parameter, setting alpha and beta accordingly and then calling the parametric quantile method.
