### ISSUE TITLE
`cor` with Matrix vs Vector produces different result

### ISSUE THREAD

**Issue by darrencl** [JuliaLang/Statistics.jl#24]
Hi,

I am not a statistician here, but I am just wondering why `cor` with supplying `X` as `Matrix` produces different result compared to as `Vector` when the content is the exact same?

I am using boston housing dataset here.
```julia
julia> cor(convert(Matrix, boston[:, [:LStat]]), boston.MedV)
1×1 Array{Float64,2}:
 -0.7376627261740151

julia> cor(boston.LStat, boston.MedV)
-0.7376627261740145
```
Is this expected or a bug?

Thanks

**Comment by nalimilan** [comment]
This is just due to the way floating point computations are carried out (likely due to how BLAS groups operations or uses SIMD). The two results are approximately equal:
```julia
julia> -0.7376627261740151 ≈ -0.7376627261740145
true
```
