### ISSUE TITLE
median vs quantile inconsistency

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/Statistics.jl#89]
This is what we have now:
```
julia> using Statistics

julia> median([missing])
missing

julia> quantile([missing], 0.5)
ERROR: ArgumentError: quantiles are undefined in presence of missing values
```

**Comment by nalimilan** [comment]
Duplicate of https://github.com/JuliaLang/Statistics.jl/issues/3? Returning `missing` in the presence of `missing` values doesn't strike me as wrong. It's just like `mean([missing, 1])`. But the inconsistency with `quantile` is indeed annoying.

BTW, I often wonder whether we could just define `median` as `quantile(x, 0.5)`. Not sure whether there would be any drawbacks to this.

**Comment by bkamins** [comment]
dup, closing.

> I often wonder whether we could just define `median` as `quantile(x, 0.5)`

Given the current implementation of `medain` I think we could. However, in general it should be possible to calculate median faster than we do now using a better algorithm that is designed specifically to calculate median (maybe this is what pandas does?). CF. https://en.wikipedia.org/wiki/Median_of_medians (though I have not benchmarked it against what we do now)

**Comment by nalimilan** [comment]
OK. Though they say "find the kth smallest number" so AFAICT it would work more generally for other quantiles. Actually, [according to Wikipedia](https://en.wikipedia.org/wiki/Quickselect) it seems that the medians of medians algorithm just consists in adding one step to choose a good pivot in the quickselect algorithm that `partialsort!` uses:
> One can assure linear performance even in the worst case by using a more sophisticated pivot strategy; this is done in the median of medians algorithm. However, the overhead of computing the pivot is high, and thus this is generally not used in practice. One can combine basic quickselect with median of medians as fallback to get both fast average case performance and linear worst-case performance; this is done in introselect.

**Comment by bkamins** [comment]
Ah - you are right. For some reason I have thought (and incorrectly tested yesterday) that `partialsort!` does sort everything from `1` do `k`. Which it does not. All is good then. We could then define `median` as `quantile` I think.
