### ISSUE TITLE
Mode function is missing

### ISSUE THREAD

**Issue by lcookiel** [JuliaLang/Statistics.jl#90]
There is no mode function among central tendency functions.
I know this function [exists](https://github.com/JuliaStats/StatsBase.jl/blob/c4432ab1090f9b614d2c485683c140000cccbaac/src/scalarstats.jl) in the StatsBase module but it would be nice to have it here, too.

**Comment by nalimilan** [comment]
Closing in favor of the more general https://github.com/JuliaLang/Statistics.jl/issues/87.
